// This file is auto-generated by TanStack Router Vite plugin at build/dev time.
// Do not edit manually — it will be overwritten.

import { RootRoute, Route, Router } from '@tanstack/react-router'

const rootRoute = new RootRoute()
export const routeTree = rootRoute
